### ISSUE TITLE
Matomat wiederbeleben

### ISSUE THREAD

**Issue by lnxu303** [k4cg/k4cg-neue#15]
Matomat ist tot und hat zu wenig RAM, um ein einigermassen aktuelles Debian zu installieren.
Andere Distro?
RAM besorgen?

**Comment by koarlchen** [comment]
Nach Austausch der Festplatte, einem RAM-Update und der Installation von einem aktuellen Debian läuft der Matomat erst mal wieder auf Stand des Backups von Ende 2019.

# TODO
- [x] Backup einrichten -> Täglich aufs NAS
- [x] Kontostände zurücksetzen (mit den Ständen von Ende 2019 kann wohl eh kaum jemand etwas anfangen)
- [x] Getränkeliste und -preise anpassen
- [x] Neue Version von Heiko einspielen um Audio wieder zu aktivieren
